[workspace]
members = [
    "rs/minter"
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.73"
candid = "0.10"
ciborium = "0.2.0"
ethabi = "18.0.0"
ethnum = "1.4.0"
getrandom = "0.2.10"
hex = "0.4.3"
ic-canister-log = "0.2.0"
ic-cdk = "=0.12"
ic-cdk-macros = "0.8.0"
ic-cdk-timers = "0.6.0"
ic-ledger-types = "=0.9"
ic-stable-structures = "0.6"
icrc-ledger-types = "0.1.12"
k256 = { version = "0.13.1", default_features = false, features = ["ecdsa"] }
lazy_static = "1.4.0" 
num-traits = "0.2.15"
rustic = "=0.1.8"
rustic-macros = "0.1.6"
serde = "1.0"
serde_bytes = "0.11.19"
serde_json = "1.0"
sha2 = "0.10.7"
sha3 = "0.10.8"

